// Code generated by Kitex v0.9.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "work/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Info": kitex.NewMethodInfo(
		infoHandler,
		newUserServiceInfoArgs,
		newUserServiceInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AvatarUpload": kitex.NewMethodInfo(
		avatarUploadHandler,
		newUserServiceAvatarUploadArgs,
		newUserServiceAvatarUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AuthMfaQrcode": kitex.NewMethodInfo(
		authMfaQrcodeHandler,
		newUserServiceAuthMfaQrcodeArgs,
		newUserServiceAuthMfaQrcodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AuthMfaBind": kitex.NewMethodInfo(
		authMfaBindHandler,
		newUserServiceAuthMfaBindArgs,
		newUserServiceAuthMfaBindResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func infoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceInfoArgs)
	realResult := result.(*user.UserServiceInfoResult)
	success, err := handler.(user.UserService).Info(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceInfoArgs() interface{} {
	return user.NewUserServiceInfoArgs()
}

func newUserServiceInfoResult() interface{} {
	return user.NewUserServiceInfoResult()
}

func avatarUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAvatarUploadArgs)
	realResult := result.(*user.UserServiceAvatarUploadResult)
	success, err := handler.(user.UserService).AvatarUpload(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAvatarUploadArgs() interface{} {
	return user.NewUserServiceAvatarUploadArgs()
}

func newUserServiceAvatarUploadResult() interface{} {
	return user.NewUserServiceAvatarUploadResult()
}

func authMfaQrcodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAuthMfaQrcodeArgs)
	realResult := result.(*user.UserServiceAuthMfaQrcodeResult)
	success, err := handler.(user.UserService).AuthMfaQrcode(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAuthMfaQrcodeArgs() interface{} {
	return user.NewUserServiceAuthMfaQrcodeArgs()
}

func newUserServiceAuthMfaQrcodeResult() interface{} {
	return user.NewUserServiceAuthMfaQrcodeResult()
}

func authMfaBindHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAuthMfaBindArgs)
	realResult := result.(*user.UserServiceAuthMfaBindResult)
	success, err := handler.(user.UserService).AuthMfaBind(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAuthMfaBindArgs() interface{} {
	return user.NewUserServiceAuthMfaBindArgs()
}

func newUserServiceAuthMfaBindResult() interface{} {
	return user.NewUserServiceAuthMfaBindResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, request *user.UserRegisterRequest) (r *user.UserRegisterResponse, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Request = request
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, request *user.UserLoginRequest) (r *user.UserLoginResponse, err error) {
	var _args user.UserServiceLoginArgs
	_args.Request = request
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Info(ctx context.Context, request *user.UserInfoRequest) (r *user.UserInfoResponse, err error) {
	var _args user.UserServiceInfoArgs
	_args.Request = request
	var _result user.UserServiceInfoResult
	if err = p.c.Call(ctx, "Info", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AvatarUpload(ctx context.Context, request *user.UserAvatarUploadRequest) (r *user.UserAvatarUploadResponse, err error) {
	var _args user.UserServiceAvatarUploadArgs
	_args.Request = request
	var _result user.UserServiceAvatarUploadResult
	if err = p.c.Call(ctx, "AvatarUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AuthMfaQrcode(ctx context.Context, request *user.AuthMfaQrcodeRequest) (r *user.AuthMfaQrcodeResponse, err error) {
	var _args user.UserServiceAuthMfaQrcodeArgs
	_args.Request = request
	var _result user.UserServiceAuthMfaQrcodeResult
	if err = p.c.Call(ctx, "AuthMfaQrcode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AuthMfaBind(ctx context.Context, request *user.AuthMfaBindRequest) (r *user.AuthMfaBindResponse, err error) {
	var _args user.UserServiceAuthMfaBindArgs
	_args.Request = request
	var _result user.UserServiceAuthMfaBindResult
	if err = p.c.Call(ctx, "AuthMfaBind", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
