// Code generated by Kitex v0.9.1. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	message "work/kitex_gen/message"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InsertMessage(ctx context.Context, request *message.InsertMessageRequest, callOptions ...callopt.Option) (r *message.InsertMessageResponse, err error)
	PopMessage(ctx context.Context, request *message.PopMessageRequest, callOptions ...callopt.Option) (r *message.PopMessageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) InsertMessage(ctx context.Context, request *message.InsertMessageRequest, callOptions ...callopt.Option) (r *message.InsertMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InsertMessage(ctx, request)
}

func (p *kMessageServiceClient) PopMessage(ctx context.Context, request *message.PopMessageRequest, callOptions ...callopt.Option) (r *message.PopMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PopMessage(ctx, request)
}
