// Code generated by Kitex v0.9.1. DO NOT EDIT.
package interactservice

import (
	server "github.com/cloudwego/kitex/server"
	interact "work/kitex_gen/interact"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler interact.InteractService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler interact.InteractService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
