version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: 'work_mysql'
    volumes:
      - ../pkg/configs/sql:/docker-entrypoint-initdb.d
      - ../pkg/data/sql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    privileged: true
    environment:
      - MYSQL_DATABASE=work
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

  redis:
    image: redis:7
    container_name: work_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ../pkg/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ../pkg/data/redis/:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - ${RABBIT_MQ_M_PORT}:15672
    environment:
      - TZ=${RABBIT_MQ_TZ}
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
    volumes:
      - ../pkg/data/rabbitmq:/var/lib/rabbitmq

  es01:
    image: elasticsearch:7.17.16
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ES_PORT}:9200
    volumes:
      - ../pkg/configs/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ../pkg/data/es/es01:/usr/share/elasticsearch/data
      - ../pkg/configs/es/plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  es02:
    image: elasticsearch:7.17.16
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../pkg/configs/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ../pkg/data/es/es02:/usr/share/elasticsearch/data
      - ../pkg/configs/es/plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  es03:
    image: elasticsearch:7.17.16
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../pkg/configs/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ../pkg/data/es/es03:/usr/share/elasticsearch/data
      - ../pkg/configs/es/plugins:/usr/share/elasticsearch/plugins
    networks:
      - elastic

  kib01:
    image: kibana:7.17.16
    container_name: kib01
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    volumes:
      - ../pkg/configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "${ETCD_PROT}:2379"  

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ../pkg/data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ../pkg/data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.16
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ../pkg/data/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - milvus

networks:
  elastic:
    driver: bridge
  milvus:
    driver: bridge
